---
- name: "Defining the Quadlet Service"
  ansible.builtin.set_fact:
    __service_name: gogs

- name: "Defining the Quadlet Name"
  ansible.builtin.set_fact:
    __quadlet_name: "{{ __service_name | capitalize }}"

- name: "Assuring Volumes Exists to {{ __quadlet_name }}"
  ansible.builtin.file:
    path: "{{ vol.path }}"
    mode: "{{ vol.mode | default('0755') }}"
    state: directory
    owner: "{{ vol.owner }}"
  when: vol.dir | bool
  loop: "{{ gogs_quadlet_volumes }}"
  loop_control:
    loop_var: vol

- name: "Installing Kube Pod Template to {{ __quadlet_name }}"
  ansible.builtin.template:
    src: gogs-pod.j2
    dest: "{{ __gogs_kube_pod }}"
    mode: "0644"
  notify:
    - daemon-reload
    - quadlet-restart

- name: "Installing Quadlet Kube Template to {{ __quadlet_name }}"
  ansible.builtin.template:
    src: gogs-quadlet.kube.j2
    dest: "{{ __gogs_kube_quadlet }}"
    mode: "0644"
  notify:
    - daemon-reload
    - quadlet-restart

- name: "Triggering Handlers"
  ansible.builtin.meta: flush_handlers
