---
- name: "Defining the Quadlet Service"
  ansible.builtin.set_fact:
    __service_name: gogs

- name: "Defining the Quadlet Name"
  ansible.builtin.set_fact:
    __quadlet_name: "{{ __service_name | capitalize }}"

- name: "Assuring {{ __quadlet_name }} Volumes Exists"
  ansible.builtin.file:
    path: "{{ vol.path }}"
    mode: "{{ vol.mode | default('0755') }}"
    state: directory
  loop: "{{ gogs_quadlet_volumes }}"
  loop_control:
    loop_var: vol

- name: "Installing {{ __quadlet_name }} Kube Pod Template"
  ansible.builtin.template:
    src: gogs-pod.j2
    dest: "{{ __gogs_kube_pod }}"

- name: "Installing {{ __quadlet_name }} Quadlet Kube Template"
  ansible.builtin.template:
    src: gogs-quadlet.kube.j2
    dest: "{{ __gogs_kube_quadlet }}"
  notify:
    - daemon-reload
    - quadlet-restart

- name: "Triggering Handlers"
  ansible.builtin.meta: flush_handlers
