---
# tasks file for gogs-quadlet
- name: "Including Postgresql Setup"
  ansible.builtin.include_tasks: psql_setup.yml

- name: "Including Gogs Setup"
  ansible.builtin.include_tasks: gogs_setup.yml

- name: "Including Gogs Backup Timer"
  ansible.builtin.include_tasks: gogs_timer_bkp.yml
